---
title: 'Exercise 2_2_1: Spatial Joins'
author: 'Stefan Jünger & Anne-Kathrin Stroppe'
date: 'Introduction to Geospatial Techniques for Social Scientists in R'
editor_options: 
  chunk_output_type: console
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
# custom boxes
knitr::opts_template$set(
  clues = list(box.title = "Clues",
               box.body = list(fill = "#fff9dc", colour = "black"),
               box.header = list(fill = "#ffec8b", colour = "black"),
               box.icon = "fa-search",
               box.collapse = TRUE)
)
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```


```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
In the addon of the session, we counted the charging stations located within North-Rhine Westphalia (NRW). Still, we did not show how to get a point layer of NRW charging stations ("charger_nrw").

Subset the data file yourself by relying on the spatial information of the file `charging_points_ger.csv` and a polygon of NRW. 
There are two ways to achieve this.
How many chargers are located within NRW?
```

```{block, opts.label = "clues"}
You need two datasets for that: the point layer `charging_points_ger.csv` (remember to adjust the crs) in the `./data` folder and polygons of NRW. For the latter, you can again use the `osmdata` syntax.
```

```{block, opts.label = "clues"}

There are two functions you can explore: `sf::st_join` and `sf::st_intersection()`.
The default of `sf::st_join()` will leave you with a 'left-join' and returns a data object with all hospitals and matching district information for those which are located within NRW. You can reset the option to perform an 'inner-join' and keep only the observation which lay within the predefined area (`sf::st_join(x , y, join  = "", left = FALSE)`).

```

```{r first, solution = TRUE}

library(dplyr)
library(readr)
library(sf)
library(osm)

# load charger
charger_ger <- 
  # Read charging station points datae
  readr::read_delim("./data/charging_points_ger.csv", 
                                 delim = ";") %>%
  # Filter out rows with missing longitude or latitude
  dplyr::filter(!is.na(longitude) & !is.na(latitude)) %>%
  # Convert data frame to sf object
  sf::st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>%
  # Reproject the spatial data to the desired CRS (Coordinate Reference System)
  sf::st_transform(crs = 3035) 


#  use the OSM function
nrw <-
  osmdata::getbb(
    "Nordrhein-Westfalen", 
    format_out = "sf_polygon"
  ) %>% 
  .$multipolygon %>% 
  sf::st_transform(3035)

# option 1
charger_nrw <- 
  charger_ger %>% 
  # Subset point data to sampling area
  sf::st_intersection(nrw)

# option 2
# spatial join
charger_nrw <-
  charger_ger %>%  
  sf::st_join(
    # point layer nrw
    nrw, 
    # chose intersect or within
    join = sf::st_intersects,
    # option FALSE will 
    # keep only the hospital 
    # which could be joined
    left = FALSE
  )
 
nrow(charger_nrw)
# 11081 hospitals in NRW


```


```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}

Did the operationalization of health care provision convince you? Don't you think it might be more important how many hospitals are close to survey respondents?
To test this, we want to calculate the number of hospitals (and/or hospital beds) per district in North-Rhine Westphalia.

```

```{block, opts.label = "clues"}
You need a `dplyr::as_tibble()` data frame to use the functions `dplyr::group_by()` and `dplyr::summarise()`.
```

```{block, opts.label = "clues"}
The function `dplyr::n()` allows summarizing the total count of hospitals. `sum(beds)` for summarizing the bed total per district.
```

```{r second, solution = TRUE}

nrw_districts <- 
  sf::read_sf("./data/VG250_KRS.shp") %>% 
  sf::st_transform(3035) %>% 
  sf::st_join(nrw, join = sf::st_intersects, left = FALSE)

nrw_hospitals <-  
  nrw_hospitals %>% 
  # beds were character, now numeric
  dplyr::mutate(beds = as.numeric(beds)) %>%
  # replace NAs as zeros for simplification
  replace(is.na(.), 0)


district_hospital_join <-
  nrw_hospitals %>% 
  # join the hospitals 
  # within districts
  sf::st_join(nrw_districts, join = sf::st_within) %>% 
  # use as tibble to perform
  # group by & summarise
  dplyr::as_tibble() %>% 
  dplyr::group_by(AGS) %>% 
  dplyr::summarise(
    hospital_count = dplyr::n(), 
    hospital_bed_count = sum(as.numeric(beds))
  ) %>% 
  # left join the new information
  # to the original data frame
  dplyr::left_join(nrw_districts, .) %>% 
  # select only usefull columns
  dplyr::select(AGS, hospital_count, hospital_bed_count)

summary(district_hospital_join )
```

